name: PR Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Configure
        run: |
          set -euo pipefail
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          set -euo pipefail
          cmake --build build -- -j$(nproc)

      - name: Test individual components
        run: |
          set -euo pipefail
          for dir in lib components/ComponentA components/ComponentB apps/AppManager apps/AppFoo; do
            echo "Testing CMake configuration for $dir"
            cmake -S $dir -B build/$dir >/dev/null
          done
